### ISSUE TITLE
Your HTTPS cert is expired

### ISSUE THREAD

**Issue by pgporada** [Octopussy-Project/Octopussy#649]
The certificate expired on December 3, 2017, 3:52 PM. The current time is December 5, 2017, 12:44 PM.

I see that you're using Let's Encrypt as your CA. You should look into using certbot on a cron or something similar.

**Comment by sebthebert** [comment]
@pgporada 

Thanks, working on it...

**Comment by sebthebert** [comment]
Fixed and added to crontab ! :)
