### ISSUE TITLE
Octopussy.pm website certificate expired

### ISSUE THREAD

**Issue by PenelopeFudd** [Octopussy-Project/Octopussy#655]
### Context
n/a

### Issue

The TLS certificate for https://octopussy.pm/ has expired (August 29, 2021).

**Comment by Ed1123** [comment]
Is this related with the website being down right now? (Dec 07, 2021)

**Comment by PenelopeFudd** [comment]
Nope, expired certificates won't prevent a website from starting.  The web server will serve the pages with the expired certificate until told differently.

The domain name octopussy.pm appears to have expired and been renewed 18 hours ago, and it looks like the rest of the world 
noticed the expiration but not the renewal yet, and has cached its non-existence: 
```
$ nslookup octopussy.pm 8.8.8.8

Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find octopussy.pm: NXDOMAIN

$ whois octopussy.pm | gawk -vRS="" 'NR==2 || NR==3'

domain:      octopussy.pm
status:      ACTIVE
hold:        YES
holder-c:    ANO00-FRNIC
admin-c:     ANO00-FRNIC
tech-c:      GR283-FRNIC
zone-c:      NFC1-FRNIC
nsl-id:      NSL33187-FRNIC
registrar:   GANDI
Expiry Date: 2022-12-07T01:07:21Z
created:     2011-12-07T01:07:21Z
last-update: 2021-12-07T01:34:53Z
source:      FRNIC
ns-list:     NSL33187-FRNIC
nserver:     b.dns.gandi.net
nserver:     a.dns.gandi.net
nserver:     c.dns.gandi.net
source:      FRNIC
```

I'm not sure how long it will stay cached because I'm not perfectly familiar with the internals of the DNS system, but if the octopussy.pm SOA record controls it, then the answer is either one hour (retry=3600), three hours (refresh,minimum=10800), or a week (expire=604800): 
```
$ nslookup -q=SOA octopussy.pm b.dns.gandi.net

Server:		b.dns.gandi.net
Address:	213.167.229.1#53

octopussy.pm
	origin = a.dns.gandi.net
	mail addr = hostmaster.gandi.net
	serial = 1634163750
	refresh = 10800
	retry = 3600
	expire = 604800
	minimum = 10800
```
There's one more timeout, the negative TTL, which I'm not sure how to query, but is specified with `$TTL 12345` in the BIND zone file, and might be the actual number we need.

As a point of interest, AWS sets its DNS record expiry times to 60 seconds by default, so that it can change things rapidly, at the cost of more DNS traffic, but since it's only two packets added to every connection (many packets), it's a small price to pay.

**Summary:** 
The WHOIS record is ok, the name servers are ok, it's just the rest of the world that needs to catch up.  :-)

**References:**
* https://en.wikipedia.org/wiki/Time_to_live#DNS_records

**Comment by djzort** [comment]
website and cert looks ok now

**Comment by ernstki** [comment]
Agreed, this appears fine now, and @sebthebert, the issue could be closed.
